# Generated by Django 5.1 on 2024-08-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='roll',
            new_name='phone',
        ),
    ]
