# Generated by Django 5.1 on 2024-08-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_teacher_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
